#pragma once

double valueInOnePoint(double x);
double valueInOnePoint1(double x);
double valueInTwoPoint(double x, double y);
double* getPc2();
double* getPc3();
double* getPc4();
double* getPc5();
double* getW2();
double* getW3();
double* getW4();
double* getW5();
double value(double pc[], double w[], int variable, int point);
double value1(double pc[], double w[], int point, double a, double b);
double derivate(int eta, int N, double x);
double calculatingNFunction(int N, double eta, double ksi);
double* pc2();
double* pc3();
double* pc4();
double* pc5();
double* eta4();
double* ksi4();
double* eta9();
double* ksi9();
double* eta16();
double* ksi16();
double* eta25();
double* ksi25();
double* multiplyWeights4();
double* multiplyWeights9();
double* multiplyWeights16();
double* multiplyWeights25();
double dydEta(double** oneGrid, double** matrixEta, int pc);
double dydKsi(double** oneGrid, double** matrixKsi, int pc);
double dxdEta(double** oneGrid, double** matrixEta, int pc);
double dxdKsi(double** oneGrid, double** matrixKsi, int pc);
double*** matrixJacobi(double** oneGrid, double** matrixEta, double** matrixKsi, int pc);
double*** jacobian(double*** matrixJacobian, int pc);
void print3dMatrix(double*** matrix, int pc, int a);
double** dNdX(double*** jacobian, double** matrixEta, double** matrixKsi, int pc);
double** dNdY(double*** jacobian, double** matrixEta, double** matrixKsi, int pc);
void print2dMatrix(double** matrix, int pc);
double*** hPc(double*** jacobian, double** dNdX, double** dNdY, int pc, double k);
double** finalMatrix(double*** hPc, double w[], int pc);
double* GaussElimination(double** HG, double* P, int nN);
double*** MatrixCInPc(double*** jacobian, double** UniversalInOneNode, int pc, double specificHeat, double density);
double findMin(double* T, int size);
double findMax(double* T, int size);
